name: 📊 크립토컴페어 일일 업데이트

on:
  schedule:
    - cron: '0 2 * * *'  # 매일 02:00 UTC (한국시간 11:00)
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

jobs:
  update-cryptocompare:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: |
          pip install requests

      - name: 📥 Download Latest Data from Release
        run: |
          echo "📥 기존 데이터 다운로드 중..."
          mkdir -p src/data/momentum/cryptocompare

          # cryptocompare_historical_data.json 다운로드
          curl -L -o src/data/momentum/cryptocompare/cryptocompare_historical_data.json \
            "https://github.com/${{ github.repository }}/releases/download/crypto-data-v1/cryptocompare_historical_data.json" \
            || echo "⚠️ 기존 히스토리 파일 없음 - 스크립트가 처리합니다"

          # cryptocompare_tickers.json 다운로드
          curl -L -o src/data/momentum/cryptocompare/cryptocompare_tickers.json \
            "https://github.com/${{ github.repository }}/releases/download/crypto-data-v1/cryptocompare_tickers.json" \
            || echo "⚠️ 기존 티커 파일 없음"

      - name: 🔄 Update CryptoCompare Data
        run: |
          python .github/scripts/update_cryptocompare_json.py

      - name: 📊 Check Updated Files
        run: |
          echo "📁 Updated files:"
          ls -lh src/data/momentum/cryptocompare/
          echo ""
          echo "📈 File sizes:"
          du -h src/data/momentum/cryptocompare/*

      - name: 📤 Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: crypto-data-v1
          name: "CryptoCompare Momentum Data"
          body: |
            🪙 **크립토컴페어 모멘텀 데이터** (자동 업데이트)

            - **최종 업데이트**: ${{ github.event.repository.updated_at }}
            - **코인 수**: 1000개 (상위 시가총액)
            - **데이터 소스**: CryptoCompare API

            ## 📥 다운로드
            - `cryptocompare_historical_data.json` - 전체 히스토리 데이터
            - `cryptocompare_tickers.json` - 티커 메타데이터

            ## 🔄 자동 업데이트
            매일 02:00 UTC (한국시간 11:00) 자동 업데이트됩니다.
          files: |
            src/data/momentum/cryptocompare/cryptocompare_historical_data.json
            src/data/momentum/cryptocompare/cryptocompare_tickers.json
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Complete
        run: |
          echo "✅ 크립토컴페어 데이터 업데이트 완료!"
          echo "📅 다음 업데이트: 내일 02:00 UTC (한국시간 11:00)"
          echo "📦 Release: https://github.com/${{ github.repository }}/releases/tag/crypto-data-v1"
